### ISSUE TITLE
error in batch augmenters

### ISSUE THREAD

**Issue by fabiofumarola** [fabiofumarola/ultrayolo#25]
### Description

error processing the coco dataset

```
Invalid argument: ValueError: Got dtype 'float64', which is a forbidden dtype (bool, uint16, uint32, uint64, uint128, uint256, int32, int64, int128, int256, float16, float32, float64, float96, float128, float256).
Traceback (most recent call last):

  File "/root/miniconda3/envs/dl/lib/python3.6/site-packages/tensorflow_core/python/ops/script_ops.py", line 236, in __call__
    ret = func(*args)

  File "/root/miniconda3/envs/dl/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 789, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/root/miniconda3/envs/dl/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/data_adapter.py", line 975, in generator_fn
    yield x[i]

  File "/home/car_user/git/ultrayolo/ultrayolo/datasets/datasets.py", line 357, in __getitem__
    self.max_objects, self.augmenters, self.pad_to_fixed_size)

  File "/home/car_user/git/ultrayolo/ultrayolo/datasets/common.py", line 424, in prepare_batch
    batch_images_pad, augmenters, batch_boxes_pad)

  File "/home/car_user/git/ultrayolo/ultrayolo/datasets/common.py", line 297, in __transform_batch
    batch_processed = augmenters.augment_batch(batch)

  File "/root/miniconda3/envs/dl/lib/python3.6/site-packages/imgaug/augmenters/meta.py", line 526, in augment_batch
    attr, hooks=hooks)

  File "/root/miniconda3/envs/dl/lib/python3.6/site-packages/imgaug/augmenters/meta.py", line 695, in augment_images
    hooks=hooks

  File "/root/miniconda3/envs/dl/lib/python3.6/site-packages/imgaug/augmenters/meta.py", line 3278, in _augment_images
    hooks=hooks

  File "/root/miniconda3/envs/dl/lib/python3.6/site-packages/imgaug/augmenters/meta.py", line 633, in augment_images
    hooks=hooks

  File "/root/miniconda3/envs/dl/lib/python3.6/site-packages/imgaug/augmenters/color.py", line 1289, in _augment_images
    images, CSPACE_HSV, self.from_colorspace)

  File "/root/miniconda3/envs/dl/lib/python3.6/site-packages/imgaug/augmenters/color.py", line 397, in change_colorspaces_
    images[i] = change_colorspace_(image, to_colorspace, from_colorspace)

  File "/root/miniconda3/envs/dl/lib/python3.6/site-packages/imgaug/augmenters/color.py", line 266, in change_colorspace_
    augmenter=None)

  File "/root/miniconda3/envs/dl/lib/python3.6/site-packages/imgaug/dtypes.py", line 319, in gate_dtypes
    dtype.name, ", ".join(disallowed)

ValueError: Got dtype 'float64', which is a forbidden dtype (bool, uint16, uint32, uint64, uint128, uint256, int32, int64, int128, int256, float16, float32, float64, float96, float128, float256).
```

**Comment by fabiofumarola** [comment]
The error depends on some of the augmentations that causes underflow in the images
